version: "3"
services:
  syslog-ng-relay:
    container_name: syslog-ng-relay
    hostname: syslog-ng-relay
    build:
      context: ./docker/
    restart: always
    #image: registry.altec.com.ar/syslog-ng/syslog-ng:1
    ports:
      - 5514:514/udp
    volumes:
      - ./logs:/var/log/syslog-ng
      - ./config/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
